package JMAP::API;
use strict;
use warnings;

use JSON::XS;
use JSON;
use DateTime;
use DateTime::TimeZone;
use DateTime::Event::ICal;

my $json = JSON::XS->new->utf8->canonical();

# Parse a JSCalendar floating datetime string into a DateTime in the given tz.
# Format: "YYYY-MM-DDTHH:MM:SS" or "YYYY-MM-DD" (all-day).
sub _parse_jscal_dt {
  my ($str, $tz) = @_;
  $str //= '';
  if ($str =~ /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})/) {
    return eval { DateTime->new(year=>$1,month=>$2,day=>$3,hour=>$4,minute=>$5,second=>$6,time_zone=>$tz) };
  }
  if ($str =~ /^(\d{4})-(\d{2})-(\d{2})$/) {
    return eval { DateTime->new(year=>$1,month=>$2,day=>$3,time_zone=>$tz) };
  }
  return undef;
}

# Format a DateTime as a JSCalendar recurrence-ID string (floating local time).
sub _dt_to_rid {
  my ($dt, $is_allday) = @_;
  return $is_allday ? $dt->strftime('%Y-%m-%d') : $dt->strftime('%Y-%m-%dT%H:%M:%S');
}

# Convert a JSCalendar recurrenceRule object to DateTime::Event::ICal args.
sub _jscal_rule_to_ical {
  my ($rule, $tz, $is_allday) = @_;
  my $freq = $rule->{frequency} or return ();
  my %a = (freq => $freq);
  $a{interval} = $rule->{interval} if defined $rule->{interval} && $rule->{interval} > 1;
  $a{count}    = $rule->{count}    if defined $rule->{count};
  if ($rule->{until}) {
    my $dt = _parse_jscal_dt($rule->{until}, $tz);
    $a{until} = $dt if $dt;
  }
  if ($rule->{byDay}) {
    $a{byday} = [ map {
      my $n = $_->{nthOfPeriod};
      $n ? "$n$_->{day}" : $_->{day};
    } @{$rule->{byDay}} ];
  }
  $a{bymonth}    = $rule->{byMonth}       if $rule->{byMonth};
  $a{bymonthday} = $rule->{byMonthDay}    if $rule->{byMonthDay};
  $a{bysetpos}   = $rule->{bySetPosition} if $rule->{bySetPosition};
  $a{byhour}     = $rule->{byHour}        if $rule->{byHour};
  $a{byminute}   = $rule->{byMinute}      if $rule->{byMinute};
  return %a;
}

# Expand a recurring event's occurrences within [after, before).
# Returns list of hashrefs: {id => "uid/rid", start => "local-datetime"}.
sub _expand_event_occurrences {
  my ($Self, $row, $master, $after_str, $before_str) = @_;

  my $start_str = $master->{start} // return ();
  # Handle both RFC 8984 recurrenceRules (array) and older singular recurrenceRule
  my $rules = $master->{recurrenceRules}
           // ($master->{recurrenceRule} ? [$master->{recurrenceRule}] : []);
  my $is_allday = ($start_str !~ /T/);
  my $tz_name   = $master->{timeZone} // 'UTC';
  my $tz        = eval { DateTime::TimeZone->new(name => $tz_name) }
                  // DateTime::TimeZone->new(name => 'UTC');

  my $dtstart  = _parse_jscal_dt($start_str, $tz) // return ();

  # Convert after/before (may have trailing Z) to local-format strings for comparison.
  # We ignore timezone offset — same approach as the existing string-compare filter.
  (my $after_cmp  = $after_str  // '') =~ s/Z$//;
  (my $before_cmp = $before_str // '') =~ s/Z$//;

  my $dt_after  = $after_cmp  ? _parse_jscal_dt($after_cmp,  $tz) : undef;
  my $dt_before = $before_cmp ? _parse_jscal_dt($before_cmp, $tz) : undef;

  # Build excluded set: explicit excludedRecurrenceRules + null overrides.
  my %excluded;
  $excluded{$_} = 1 for @{$master->{excludedRecurrenceRules} // []};
  my $overrides = $master->{recurrenceOverrides} // {};
  for my $rid (keys %$overrides) {
    $excluded{$rid} = 1 if !defined $overrides->{$rid} || $overrides->{$rid}{excluded};
  }

  my %seen;
  my @items;

  for my $rule (@$rules) {
    my %ical = eval { _jscal_rule_to_ical($rule, $tz, $is_allday) };
    next if $@ || !%ical;

    my $set = eval { DateTime::Event::ICal->recur(dtstart => $dtstart, %ical) };
    next if $@ || !$set;

    # Start iterator just before $dt_after (or from dtstart - 1s if no after).
    my $iter_from = $dt_after
      ? $dt_after->clone->subtract(seconds => 1)
      : $dtstart->clone->subtract(seconds => 1);
    my $iter = $set->iterator(after => $iter_from);

    my $safety = 5000;
    while (my $dt = $iter->next) {
      last unless --$safety;
      last if $dt_before && DateTime->compare($dt, $dt_before) >= 0;
      my $rid = _dt_to_rid($dt, $is_allday);
      next if $excluded{$rid};
      next if $seen{$rid}++;

      my $override     = $overrides->{$rid} // {};
      my $actual_start = $override->{start} // $rid;
      next if $after_cmp  && $actual_start lt $after_cmp;
      next if $before_cmp && $actual_start ge $before_cmp;

      push @items, { id => "$row->{eventuid}/$rid", start => $actual_start };
    }
  }

  # Include moved overrides whose actual start lands in range but natural
  # occurrence was outside (so not generated by the iterator above).
  for my $rid (sort keys %$overrides) {
    next unless defined $overrides->{$rid};
    next if $overrides->{$rid}{excluded};
    next if $seen{$rid};
    my $actual_start = $overrides->{$rid}{start} // $rid;
    next if $after_cmp  && $actual_start lt $after_cmp;
    next if $before_cmp && $actual_start ge $before_cmp;
    push @items, { id => "$row->{eventuid}/$rid", start => $actual_start };
  }

  return @items;
}

sub _is_origin {
  my ($organizer, $user_email) = @_;
  return JSON::true unless defined $organizer;
  my $org_email = lc($organizer =~ s{^mailto:}{}ri);
  return (lc($user_email // '') eq $org_email) ? JSON::true : JSON::false;
}

sub getCalendarPreferences {
  return ['calendarPreferences', {
    autoAddCalendarId         => '',
    autoAddInvitations        => JSON::false,
    autoAddGroupId            => JSON::null,
    autoRSVPGroupId           => JSON::null,
    autoRSVP                  => JSON::false,
    autoUpdate                => JSON::false,
    birthdaysAreVisible       => JSON::false,
    defaultAlerts             => {},
    defaultAllDayAlerts       => {},
    defaultCalendarId         => '',
    firstDayOfWeek            => 1,
    markReadAndFileAutoAdd    => JSON::false,
    markReadAndFileAutoUpdate => JSON::false,
    onlyAutoAddIfInGroup      => JSON::false,
    onlyAutoRSVPIfInGroup     => JSON::false,
    showWeekNumbers           => JSON::false,
    timeZone                  => JSON::null,
    useTimeZones              => JSON::false,
  }];
}

sub api_Calendar_get {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newState = "$user->{jstateCalendar}";

  my $data = $Self->{db}->dget('jcalendars', { active => 1 });

  my %want;
  if ($args->{ids}) {
    %want = map { $Self->idmap($_) => 1 } @{$args->{ids}};
  }
  else {
    %want = map { $_->{jcalendarid} => 1 } @$data;
  }

  my @list;

  foreach my $item (@$data) {
    next unless delete $want{$item->{jcalendarid}};

    my %rec = (
      id                     => "$item->{jcalendarid}",
      name                   => "$item->{name}",
      color                  => "$item->{color}",
      sortOrder              => $item->{sortOrder}  || 0,
      isDefault              => $item->{isDefault}  ? $JSON::true : $JSON::false,
      isSubscribed           => $JSON::true,
      includeInAvailability  => $item->{includeInAvailability} || 'all',
      isVisible              => $item->{isVisible}  ? $JSON::true : $JSON::false,
      myRights => {
        mayReadFreeBusy  => $item->{mayReadFreeBusy}  ? $JSON::true : $JSON::false,
        mayReadItems     => $item->{mayReadItems}     ? $JSON::true : $JSON::false,
        mayWriteAll      => $item->{mayAddItems}      ? $JSON::true : $JSON::false,
        mayWriteOwn      => $item->{mayAddItems}      ? $JSON::true : $JSON::false,
        mayUpdatePrivate => $item->{mayModifyItems}   ? $JSON::true : $JSON::false,
        mayRSVP          => $JSON::false,
        mayAdmin         => $item->{mayDelete}        ? $JSON::true : $JSON::false,
        mayDelete        => $item->{mayDelete}        ? $JSON::true : $JSON::false,
      },
    );

    foreach my $key (keys %rec) {
      delete $rec{$key} unless _prop_wanted($args, $key);
    }

    push @list, \%rec;
  }

  $Self->commit();

  my %missingids = %want;

  return ['Calendar/get', {
    list => \@list,
    accountId => $accountid,
    state => $newState,
    notFound => [map { "$_" } keys %missingids],
  }];
}

sub api_Calendar_changes {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newState = "$user->{jstateCalendar}";

  my @e = $Self->_check_since_state($args, $user, $newState);
  return @e if @e;
  my $sinceState = $args->{sinceState};

  my $data = $Self->{db}->dget('jcalendars', {}, 'jcalendarid,jmodseq,active,jcreated');

  if ($args->{maxChanges} and @$data > $args->{maxChanges}) {
    return $Self->_transError(['error', {type => 'cannotCalculateChanges', newState => $newState}]);
  }

  $Self->commit();

  my @changed = grep { $_->{jmodseq} > $sinceState } @$data;
  my ($created, $updated, $destroyed) = $Self->_classify_changes(\@changed, $sinceState, 'jcalendarid');

  my @res = (['Calendar/changes', {
    accountId => $accountid,
    oldState => "$sinceState",
    newState => $newState,
    created => [map { "$_" } @$created],
    updated => [map { "$_" } @$updated],
    destroyed => [map { "$_" } @$destroyed],
    hasMoreChanges => JSON::false,
  }]);

  return @res;
}

sub api_Calendar_set {
  my $Self = shift;
  my $args = shift;

  $Self->begin();

  my $accountid = $Self->{db}->accountid();
  return $Self->_transError(['error', {type => 'accountNotFound'}])
    if ($args->{accountId} and $args->{accountId} ne $accountid);

  $Self->commit();

  my $create = $args->{create} || {};
  my $update = $args->{update} || {};
  my $destroy = $args->{destroy} || [];

  my ($created, $notCreated, $updated, $notUpdated, $destroyed, $notDestroyed);
  my ($oldState, $newState);

  my $scoped_lock = $Self->{db}->begin_superlock();

  $Self->{db}->sync_calendars();

  $Self->begin();
  my $user = $Self->{db}->get_user();
  $oldState = "$user->{jstateCalendar}";
  $Self->commit();

  ($created, $notCreated) = $Self->{db}->create_calendars($create);
  $Self->setid($_, $created->{$_}{id}) for keys %$created;
  $Self->_resolve_patch($update, 'api_Calendar_get');
  ($updated, $notUpdated) = $Self->{db}->update_calendars($update, sub { $Self->idmap(shift) });

  my $onDestroyRemoveEvents = $args->{onDestroyRemoveEvents} ? 1 : 0;
  my (@safe_destroy, %notDestroyed_pre);
  for my $jcalendarid (@$destroy) {
    $Self->begin();
    my $has_events = $Self->{db}->dcount('jevents', { jcalendarid => $jcalendarid, active => 1 });
    my $event_uids = $has_events
      ? $Self->{db}->dgetcol('jevents', { jcalendarid => $jcalendarid, active => 1 }, 'eventuid')
      : [];
    $Self->commit();
    if ($has_events && !$onDestroyRemoveEvents) {
      $notDestroyed_pre{$jcalendarid} = { type => 'calendarHasEvent' };
    } else {
      $Self->{db}->destroy_calendar_events($event_uids) if @$event_uids;
      push @safe_destroy, $jcalendarid;
    }
  }

  ($destroyed, $notDestroyed) = $Self->{db}->destroy_calendars(\@safe_destroy);
  for my $id (keys %notDestroyed_pre) {
    $notDestroyed->{$id} = $notDestroyed_pre{$id};
  }

  # XXX - cheap dumb racy version
  $Self->{db}->sync_calendars();

  $Self->begin();
  $user = $Self->{db}->get_user();
  $newState = "$user->{jstateCalendar}";
  $Self->commit();

  my @res;
  push @res, ['Calendar/set', {
    accountId => $accountid,
    oldState => $oldState,
    newState => $newState,
    created => _nullempty($created),
    notCreated => _nullempty($notCreated),
    updated => _nullempty($updated),
    notUpdated => _nullempty($notUpdated),
    destroyed => _nullempty($destroyed),
    notDestroyed => _nullempty($notDestroyed),
  }];

  return @res;
}

# Parse an ISO 8601 duration string into seconds (approximate for Y/M).
sub _iso_duration_to_seconds {
  my ($dur) = @_;
  return 0 unless defined $dur && $dur =~ /^P/;
  my $s = 0;
  $s += $1 * 365 * 86400 if $dur =~ /(\d+)Y/;
  $s += $1 *  30 * 86400 if $dur =~ /(\d+)M(?=[^T]*$)/;  # months (before T)
  $s += $1*   7 * 86400  if $dur =~ /(\d+)W/;
  $s += $1 *     86400   if $dur =~ /(\d+)D/;
  $s += $1 *      3600   if $dur =~ /T.*?(\d+)H/;
  $s += $1 *        60   if $dur =~ /T.*?(\d+)M/;
  $s += $1               if $dur =~ /T.*?(\d+)S/;
  return int($s);
}

# Return a floating ISO datetime string for start + duration, or undef on parse failure.
sub _event_end_dt {
  my ($start, $duration) = @_;
  my $dt = _parse_jscal_dt($start, 'floating');
  return undef unless $dt;
  $dt->add(seconds => _iso_duration_to_seconds($duration // 'PT0S'));
  return $dt->strftime('%Y-%m-%dT%H:%M:%S');
}

sub _event_match {
  my $Self = shift;
  my ($item, $condition, $storage) = @_;

  if ($condition->{inCalendar}) {
    return 0 unless $item->{jcalendarid} eq $condition->{inCalendar};
  }
  if ($condition->{inCalendars}) {
    my %cal_set = map { $_ => 1 } @{$condition->{inCalendars}};
    return 0 unless $cal_set{$item->{jcalendarid}};
  }

  if (defined $condition->{uid}) {
    return 0 unless $item->{eventuid} eq $condition->{uid};
  }

  my $needs_payload = grep { defined $condition->{$_} }
      qw(after before text title description location owner attendee);

  if ($needs_payload) {
    my $uid     = $item->{eventuid};
    my $payload = $storage->{$uid} //= $Self->{db}->read_jevent_payload($uid) // {};

    if ($condition->{after} || $condition->{before}) {
      my $start      = $payload->{start} // '';
      my $is_recur   = $payload->{recurrenceRules} || $payload->{recurrenceRule};
      unless ($is_recur) {
        (my $before_cmp = $condition->{before} // '') =~ s/Z$//;
        (my $after_cmp  = $condition->{after}  // '') =~ s/Z$//;
        return 0 if $before_cmp && $start ge $before_cmp;
        if ($after_cmp) {
          my $end = _event_end_dt($start, $payload->{duration}) // $start;
          return 0 if $end le $after_cmp;
        }
      }
    }

    if (defined $condition->{title}) {
      return 0 unless index(lc($payload->{title} // ''), lc($condition->{title})) >= 0;
    }

    if (defined $condition->{description}) {
      return 0 unless index(lc($payload->{description} // ''), lc($condition->{description})) >= 0;
    }

    if (defined $condition->{location}) {
      my $needle = lc($condition->{location});
      my $found  = 0;
      for my $loc (values %{$payload->{locations} || {}}) {
        if (index(lc($loc->{name} // ''), $needle) >= 0) { $found = 1; last }
      }
      return 0 unless $found;
    }

    if (defined $condition->{owner}) {
      my $needle = lc($condition->{owner});
      my $found  = 0;
      for my $addr (values %{$payload->{replyTo} || {}}) {
        (my $e = $addr) =~ s/^mailto://i;
        if (index(lc($e), $needle) >= 0) { $found = 1; last }
      }
      unless ($found) {
        for my $p (values %{$payload->{participants} || {}}) {
          next unless ($p->{roles} || {})->{owner};
          for my $addr (values %{$p->{sendTo} || {}}) {
            (my $e = $addr) =~ s/^mailto://i;
            if (index(lc($p->{name} // ''), $needle) >= 0 ||
                index(lc($e), $needle) >= 0) { $found = 1; last }
          }
          last if $found;
        }
      }
      return 0 unless $found;
    }

    if (defined $condition->{attendee}) {
      my $needle = lc($condition->{attendee});
      my $found  = 0;
      for my $p (values %{$payload->{participants} || {}}) {
        for my $addr (values %{$p->{sendTo} || {}}) {
          (my $e = $addr) =~ s/^mailto://i;
          if (index(lc($p->{name} // ''), $needle) >= 0 ||
              index(lc($e), $needle) >= 0) { $found = 1; last }
        }
        last if $found;
      }
      return 0 unless $found;
    }

    if (defined $condition->{text}) {
      my $needle   = lc($condition->{text});
      my @hayparts = (
        $payload->{title}       // '',
        $payload->{description} // '',
        map { $_->{name} // '' } values %{$payload->{locations}    || {}},
        map {
          my $p = $_;
          ($p->{name} // ''),
          map { (my $e = $_) =~ s/^mailto://i; $e } values %{$p->{sendTo} || {}}
        } values %{$payload->{participants} || {}},
      );
      return 0 unless index(lc(join(' ', @hayparts)), $needle) >= 0;
    }
  }

  return 1;
}

sub _event_filter {
  my $Self = shift;
  my ($data, $filter, $storage) = @_;
  my @res;
  foreach my $item (@$data) {
    next unless $Self->_event_match($item, $filter, $storage);
    push @res, $item;
  }
  return \@res;
}

sub api_CalendarEvent_query {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newQueryState = "$user->{jstateCalendarEvent}";

  my $data = $Self->{db}->dget('jevents', { active => 1 }, 'eventuid,jcalendarid');

  return $Self->_transError(['error', {type => 'invalidArguments', arguments => ['position']}])
    if ($args->{position} // 0) < 0;

  if ($args->{expandRecurrences}) {
    my $filter  = $args->{filter} // {};
    my $after   = $filter->{after};
    my $before  = $filter->{before};
    my %storage;

    # inCalendar / inCalendars pre-filter (avoids loading payloads for wrong calendars)
    if ($filter->{inCalendar}) {
      $data = [ grep { $_->{jcalendarid} eq $filter->{inCalendar} } @$data ];
    }
    if ($filter->{inCalendars}) {
      my %cal_set = map { $_ => 1 } @{$filter->{inCalendars}};
      $data = [ grep { $cal_set{$_->{jcalendarid}} } @$data ];
    }

    my @expanded;
    for my $row (@$data) {
      my $master = $Self->{db}->read_jevent_payload($row->{eventuid});
      next unless $master;

      $storage{ $row->{eventuid} } = $master;
      next unless $Self->_event_match($row, $filter, \%storage);

      my $is_recurring = ($master->{recurrenceRules} && @{$master->{recurrenceRules}})
                      || $master->{recurrenceRule};
      if ($is_recurring) {
        push @expanded, $Self->_expand_event_occurrences($row, $master, $after, $before);
      } else {
        push @expanded, { id => $row->{eventuid}, start => $master->{start} // '' };
      }
    }

    @expanded = sort { $a->{start} cmp $b->{start} } @expanded;

    my ($wstart, $wend) = $Self->_apply_window(\@expanded, $args, sub { $_[0]{id} });
    return $Self->_transError(['error', {type => 'anchorNotFound'}]) unless defined $wstart;

    my @ids = map { $expanded[$_]{id} } $wstart..$wend;
    my $total = scalar @expanded;

    $Self->commit();

    return ['CalendarEvent/query', {
      accountId          => $accountid,
      filter             => $args->{filter},
      sort               => $args->{sort},
      queryState         => $newQueryState,
      canCalculateChanges => JSON::false,
      position           => $wstart,
      total              => $total,
      ids                => [map { "$_" } @ids],
    }];
  }

  my %storage;
  $data = $Self->_event_filter($data, $args->{filter}, \%storage) if $args->{filter};

  if ($args->{sort}) {
    my %valid = map { $_ => 1 } qw(start uid);
    for my $cmp (@{$args->{sort}}) {
      return $Self->_transError(['error', {type => 'unsupportedSort', sort => $cmp}])
        unless $valid{$cmp->{property} // ''};
    }
    $data = [sort {
      my $res = 0;
      for my $cmp (@{$args->{sort}}) {
        if ($cmp->{property} eq 'start') {
          $storage{$a->{eventuid}} //= $Self->{db}->read_jevent_payload($a->{eventuid}) // {};
          $storage{$b->{eventuid}} //= $Self->{db}->read_jevent_payload($b->{eventuid}) // {};
          $res = ($storage{$a->{eventuid}}{start} // '') cmp ($storage{$b->{eventuid}}{start} // '');
        } elsif ($cmp->{property} eq 'uid') {
          $res = $a->{eventuid} cmp $b->{eventuid};
        }
        $res = -$res if defined($cmp->{isAscending}) && !$cmp->{isAscending};
        last if $res;
      }
      $res || ($a->{eventuid} cmp $b->{eventuid});
    } @$data];
  }

  my ($start, $end) = $Self->_apply_window($data, $args, sub { $_[0]{eventuid} });
  return $Self->_transError(['error', {type => 'anchorNotFound'}]) unless defined $start;

  my @result = map { $data->[$_]{eventuid} } $start..$end;

  $Self->commit();

  return ['CalendarEvent/query', {
    accountId => $accountid,
    filter => $args->{filter},
    sort => $args->{sort},
    queryState => $newQueryState,
    position => $start,
    total => scalar(@$data),
    ids => [map { "$_" } @result],
  }];
}

sub _expand_occurrence {
  my ($master, $recurrence_id) = @_;

  my $overrides = $master->{recurrenceOverrides} || {};

  # Explicitly excluded occurrence
  return undef if exists $overrides->{$recurrence_id}
    && (!defined $overrides->{$recurrence_id} || $overrides->{$recurrence_id}{excluded});

  my %item  = %$master;
  my $patch = $overrides->{$recurrence_id} || {};
  $item{$_} = $patch->{$_} for keys %$patch;

  # start: override's value if it was moved, otherwise the scheduled recurrenceId
  $item{start}       = exists $patch->{start} ? $patch->{start} : $recurrence_id;
  $item{recurrenceId} = $recurrence_id;

  # master-only properties are not valid on expanded occurrences (RFC 8984 §4.3)
  delete $item{$_} for qw(recurrenceRules recurrenceOverrides excludedRecurrenceRules);

  return \%item;
}

sub api_CalendarEvent_get {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newState = "$user->{jstateCalendarEvent}";

  return $Self->_transError(['error', {type => 'invalidArguments', arguments => ['ids']}])
    unless $args->{ids};

  my %seenids;
  my %missingids;
  my @list;
  foreach my $eventuid (map { $Self->idmap($_) } @{$args->{ids}}) {
    next if $seenids{$eventuid};
    $seenids{$eventuid} = 1;

    # Occurrence ID: masterUid/recurrenceId
    if ($eventuid =~ m{^([^/]+)/(.+)$}) {
      my ($master_uid, $recurrence_id) = ($1, $2);

      my $data = $Self->{db}->dgetone('jevents', { eventuid => $master_uid, active => 1 }, 'jcalendarid');
      unless ($data) {
        $missingids{$eventuid} = 1;
        next;
      }

      my $master = $Self->{db}->read_jevent_payload($master_uid);
      unless ($master) {
        $missingids{$eventuid} = 1;
        next;
      }

      my $item = _expand_occurrence($master, $recurrence_id);
      unless ($item) {
        $missingids{$eventuid} = 1;  # excluded occurrence
        next;
      }

      my $organizer = $item->{organizerCalendarAddress};
      foreach my $key (keys %$item) {
        delete $item->{$key} unless _prop_wanted($args, $key);
      }
      $item->{id}          = $eventuid;
      $item->{calendarIds} = { "$data->{jcalendarid}" => JSON::true } if _prop_wanted($args, 'calendarIds');
      $item->{isOrigin}    = _is_origin($organizer, $user->{email})   if _prop_wanted($args, 'isOrigin');
      push @list, $item;
      next;
    }

    # Master event
    my $data = $Self->{db}->dgetone('jevents', { eventuid => $eventuid, active => 1 }, 'jcalendarid');
    unless ($data) {
      $missingids{$eventuid} = 1;
      next;
    }

    my $item = $Self->{db}->read_jevent_payload($eventuid);
    unless ($item) {
      $missingids{$eventuid} = 1;
      next;
    }

    my $organizer = $item->{organizerCalendarAddress};
    foreach my $key (keys %$item) {
      delete $item->{$key} unless _prop_wanted($args, $key);
    }

    $item->{id}          = $eventuid;
    $item->{calendarIds} = { "$data->{jcalendarid}" => JSON::true } if _prop_wanted($args, "calendarIds");
    $item->{isOrigin}    = _is_origin($organizer, $user->{email})   if _prop_wanted($args, 'isOrigin');

    push @list, $item;
  }

  $Self->commit();

  return ['CalendarEvent/get', {
    list => \@list,
    accountId => $accountid,
    state => $newState,
    notFound => [map { "$_" } keys %missingids],
  }];
}

sub api_CalendarEvent_changes {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newState = "$user->{jstateCalendarEvent}";

  my @e = $Self->_check_since_state($args, $user, $newState);
  return @e if @e;

  my $data = $Self->{db}->dget('jevents', { jmodseq => ['>', $args->{sinceState}] }, 'eventuid,active,jcreated');

  if ($args->{maxChanges} and @$data > $args->{maxChanges}) {
    return $Self->_transError(['error', {type => 'cannotCalculateChanges', newState => $newState}]);
  }

  $Self->commit();

  my ($created, $updated, $destroyed) = $Self->_classify_changes($data, $args->{sinceState}, 'eventuid');

  my @res;
  push @res, ['CalendarEvent/changes', {
    accountId => $accountid,
    oldState => "$args->{sinceState}",
    newState => $newState,
    created => [map { "$_" } @$created],
    updated => [map { "$_" } @$updated],
    destroyed => [map { "$_" } @$destroyed],
    hasMoreChanges => JSON::false,
  }];

  return @res;
}

sub api_CalendarEvent_queryChanges {
  my $Self = shift;
  my $args = shift;

  my ($user, $accountid) = $Self->_api_init($args);
  return $Self->_transError(['error', {type => 'accountNotFound'}]) unless defined $accountid;

  my $newQueryState = "$user->{jstateCalendarEvent}";
  my $sinceQueryState = $args->{sinceQueryState};
  return $Self->_transError(['error', {type => 'invalidArguments', arguments => ['sinceQueryState']}])
    unless $sinceQueryState;
  return $Self->_transError(['error', {type => 'cannotCalculateChanges', newQueryState => $newQueryState}])
    if ($user->{jdeletedmodseq} and $sinceQueryState <= $user->{jdeletedmodseq});

  my $data = $Self->{db}->dget('jevents', { active => 1 }, 'eventuid,jmodseq');
  my $total = scalar @$data;

  my %idx;
  my $i = 0;
  $idx{$_->{eventuid}} = $i++ for @$data;

  my $changed = $Self->{db}->dget('jevents', { jmodseq => ['>', $sinceQueryState] }, 'eventuid,active');

  $Self->commit();

  my @added;
  my @destroyed;
  for my $row (@$changed) {
    push @destroyed, "$row->{eventuid}";
    if ($row->{active} && exists $idx{$row->{eventuid}}) {
      push @added, { id => "$row->{eventuid}", index => $idx{$row->{eventuid}} };
    }
  }

  return ['CalendarEvent/queryChanges', {
    accountId     => $accountid,
    filter        => $args->{filter},
    sort          => $args->{sort},
    oldQueryState => "$sinceQueryState",
    newQueryState => $newQueryState,
    total         => $total,
    removed       => \@destroyed,
    added         => \@added,
  }];
}

sub api_CalendarEvent_copy {
  my $Self = shift;
  my $args = shift;
  my $accountid = $Self->{db}->accountid();
  return ['error', { type => 'notImplemented' }];
}

sub api_CalendarEvent_parse {
  my $Self = shift;
  my $args = shift;
  return ['error', { type => 'notImplemented' }];
}

sub api_CalendarEvent_set {
  my $Self = shift;
  my $args = shift;

  $Self->begin();

  my $user = $Self->{db}->get_user();
  my $accountid = $Self->{db}->accountid();
  return $Self->_transError(['error', {type => 'accountNotFound'}])
    if ($args->{accountId} and $args->{accountId} ne $accountid);

  $Self->commit();

  my $create = $args->{create} || {};
  my $update = $args->{update} || {};
  my $destroy = $args->{destroy} || [];

  my ($created, $notCreated, $updated, $notUpdated, $destroyed, $notDestroyed);
  my ($oldState, $newState);

  my $scoped_lock = $Self->{db}->begin_superlock();

  $Self->{db}->sync_calendars();

  $Self->begin();
  $user = $Self->{db}->get_user();
  $oldState = "$user->{jstateCalendarEvent}";
  $Self->commit();

  ($created, $notCreated) = $Self->{db}->create_calendar_events($create);
  $Self->setid($_, $created->{$_}{id}) for keys %$created;
  $Self->_resolve_patch($update, 'api_CalendarEvent_get');
  ($updated, $notUpdated) = $Self->{db}->update_calendar_events($update, sub { $Self->idmap(shift) });
  ($destroyed, $notDestroyed) = $Self->{db}->destroy_calendar_events($destroy);

  # XXX - cheap dumb racy version
  $Self->{db}->sync_calendars();

  $Self->begin();
  $user = $Self->{db}->get_user();
  $newState = "$user->{jstateCalendarEvent}";
  $Self->commit();

  my @res;
  push @res, ['CalendarEvent/set', {
    accountId => $accountid,
    oldState => $oldState,
    newState => $newState,
    created => _nullempty($created),
    notCreated => _nullempty($notCreated),
    updated => _nullempty($updated),
    notUpdated => _nullempty($notUpdated),
    destroyed => _nullempty($destroyed),
    notDestroyed => _nullempty($notDestroyed),
  }];

  return @res;
}

sub api_ParticipantIdentity_get {
  my $Self = shift;
  my $args = shift;
  $Self->begin();
  my $user = $Self->{db}->get_user();
  my $accountid = $Self->{db}->accountid();
  $Self->commit();

  my $email = $user->{email} // '';
  my @identities;
  my @notFound;

  if ($args->{ids}) {
    for my $id (@{$args->{ids}}) {
      if ($email && $id eq 'id1') {
        push @identities, { id => 'id1', name => '', sendTo => { imip => "mailto:$email" } };
      } else {
        push @notFound, "$id";
      }
    }
  } elsif ($email) {
    push @identities, { id => 'id1', name => '', sendTo => { imip => "mailto:$email" } };
  }

  return ['ParticipantIdentity/get', {
    accountId => $accountid,
    state     => "$user->{jhighestmodseq}",
    list      => \@identities,
    notFound  => \@notFound,
  }];
}

sub api_ParticipantIdentity_changes {
  my $Self = shift;
  my $args = shift;
  $Self->begin();
  my $user = $Self->{db}->get_user();
  my $accountid = $Self->{db}->accountid();
  $Self->commit();
  my $state = "$user->{jhighestmodseq}";
  return ['ParticipantIdentity/changes', {
    accountId      => $accountid,
    oldState       => $args->{sinceState} // $state,
    newState       => $state,
    created        => [],
    updated        => [],
    destroyed      => [],
    hasMoreChanges => JSON::false,
  }];
}

sub api_ParticipantIdentity_set {
  my $Self = shift;
  my $args = shift;
  $Self->begin();
  my $user = $Self->{db}->get_user();
  my $accountid = $Self->{db}->accountid();
  $Self->commit();
  my $state = "$user->{jhighestmodseq}";
  my %notCreated  = map { $_ => { type => 'forbidden' } } keys %{$args->{create}  || {}};
  my %notUpdated  = map { $_ => { type => 'forbidden' } } keys %{$args->{update}  || {}};
  my %notDestroyed = map { $_ => { type => 'forbidden' } } @{$args->{destroy} || []};
  return ['ParticipantIdentity/set', {
    accountId    => $accountid,
    oldState     => $state,
    newState     => $state,
    created      => undef,
    notCreated   => _nullempty(\%notCreated),
    updated      => undef,
    notUpdated   => _nullempty(\%notUpdated),
    destroyed    => undef,
    notDestroyed => _nullempty(\%notDestroyed),
  }];
}

1;
